// Twitter => Display name
const members = new Map([
  ["bullishtrader", "The Bull"],
  ["unclebadgers", "UncleBadgers"],
  ["baloneybones", "Baloney Bones"],
  ["rylucid", "Rylucid"],
  ["_Jonsie_", "Jonsie"],
  ["degentrified", "degentrified"],
  ["slavetosound", "slavetosound"],
  ["thor_rune_dad", "john (thordad)"],
  ["thormaximalist", "THORchain.BULL"],
  ["slatttophy", "slattTophy"],
  ["tharebear", "Tharebear"],
  ["8kalani8", "kalani"],
  ["howefai", "howefai"],
  ["_realcosmos", "AIRTX"],
  ["opaopaque", "Opaque"],
  ["warlockofmirth", "MoDee227"],
  ["thorlunatic", "shaye"],
  ["hoodlum1349", "Hoodlum"],
  ["v__RaBBiT__v", "vRabbitv"],
  ["bountyxxhunter", "Demandalorian"],
  ["jimbobkos", "Jimbobkos"],
  ["fakk2", "Juggernaut"],
  ["andytcrypto", "ANDY"],
  ["wraitheonn", "TacticalMinivan"],
  ["drismegistus", "mcbeaster"],
  ["hue53637781", "hue"],
  ["0xnguyen", "0xNguyen"],
  ["nighthoch", "memechoi"],
  ["tehslaw", "TehColeSlaw"],
  ["tratium", "tratium"],
  ["archon_0x", "Archon"],
  ["0xernestN", "IShotTheSheriff"],
  ["mehfysto", "MehFysto"],
  ["runeForrestRune", "Ados"],
  ["TheMrRhomboid", "MrRhomboid"],
  ["thorlafr", "Olaf"],
  ["0xframsynt", "Framsynt"],
  ["0xNappyCaps", "NappyCaps"],
  ["PromisQ_", "Jative"],
  ["Dreisenhorn", "Eisenhorn"],
  ["jahverkhovykh", "Jah"],
  ["tbarret", "Erondil"],
  ["CashflowMagi", "cashflow.magi"],
  ["Tmc1908", "TMc1908"],
  ["0xbankai", "Bankai"],
  ["RankinsJ", "JRinc"],
  ["0xBakou", "Bakou"],
  ["0xSmith", "Smith"],
  ["coinzycapital", "CoinzyCapital"],
  ["eatmybifrost", "bifrosticle"],
  ["finalfinance_", "Newcompdog"],
  ["grabnarsergej", "sergo"],
  ["jatinkkalra", "Jatin Kalra"],
  ["keith_0x", "Runeingman"],
  ["0xPluto", "Pluto"],
  ["TamerOvutmen", "Tamer"],
  ["wagmi42069", "wagmi"],
  ["TheTickrate", "Tickrate"],
  ["theautomatona", "Wabbit"],
  ["BumQuack1337", "Ochhii"],
  ["0x_luc", "0xLuc"],
  ["thorchain_newby", "Thorchain.Newbie"],
]);

export default members;